It537 selin
mkaanilhan/IT537-2024-Assignment-2 pull request #4
Opened 2024-07-08 14:00 UTC by RenaCet

2024-07-09 06:47 UTC, mkaanilhan requested changes
Ana ekranda load more yada pagination yok sadece 20 tane görebiliyorum.

Bir de bu açtığın RenaCet:IT537_Selin branch'inde yeni commit girersen tekrardan pull request açmana gerek olmaz. Direk burdan süreç devam edebilir.

2024-07-09 06:53 UTC, RenaCet commented
Selamlar,

Evet 20 tane getirecek şekilde yapmıştım, hepsini de getirtebilirim.

Süper tamamdır o zaman aynı branche commit gireyim :)

Teşekkürler.

9 Tem 2024 Sal, saat 09:47 tarihinde mkaanilhan ***@***.***>
şunu yazdı:

> ***@***.**** requested changes on this pull request.
>
> Ana ekranda load more yada pagination yok sadece 20 tane görebiliyorum.
>
> Bir de bu açtığın RenaCet:IT537_Selin branch'inde yeni commit girersen
> tekrardan pull request açmana gerek olmaz. Direk burdan süreç devam
> edebilir.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mkaanilhan/IT537-2024-Assignment-2/pull/4#pullrequestreview-2165209979>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BIZDSGRBW5TLUEUGBPF4OW3ZLOBQ5AVCNFSM6AAAAABKQ5B75KVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNRVGIYDSOJXHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-07-09 07:32 UTC, RenaCet commented
Şimdi load more’u da ekledim ve commit yaptım.

9 Tem 2024 Sal, saat 09:53 tarihinde selin rena ***@***.***> şunu
yazdı:

> Selamlar,
>
> Evet 20 tane getirecek şekilde yapmıştım, hepsini de getirtebilirim.
>
> Süper tamamdır o zaman aynı branche commit gireyim :)
>
> Teşekkürler.
>
> 9 Tem 2024 Sal, saat 09:47 tarihinde mkaanilhan ***@***.***>
> şunu yazdı:
>
>> ***@***.**** requested changes on this pull request.
>>
>> Ana ekranda load more yada pagination yok sadece 20 tane görebiliyorum.
>>
>> Bir de bu açtığın RenaCet:IT537_Selin branch'inde yeni commit girersen
>> tekrardan pull request açmana gerek olmaz. Direk burdan süreç devam
>> edebilir.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/mkaanilhan/IT537-2024-Assignment-2/pull/4#pullrequestreview-2165209979>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/BIZDSGRBW5TLUEUGBPF4OW3ZLOBQ5AVCNFSM6AAAAABKQ5B75KVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNRVGIYDSOJXHE>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2024-07-09 09:58 UTC, RenaCet commented
Bu şekilde başka düzeltmem gereken bir nokta var mıdır?

9 Tem 2024 Sal, saat 10:32 tarihinde selin rena ***@***.***> şunu
yazdı:

> Şimdi load more’u da ekledim ve commit yaptım.
>
> 9 Tem 2024 Sal, saat 09:53 tarihinde selin rena ***@***.***>
> şunu yazdı:
>
>> Selamlar,
>>
>> Evet 20 tane getirecek şekilde yapmıştım, hepsini de getirtebilirim.
>>
>> Süper tamamdır o zaman aynı branche commit gireyim :)
>>
>> Teşekkürler.
>>
>> 9 Tem 2024 Sal, saat 09:47 tarihinde mkaanilhan ***@***.***>
>> şunu yazdı:
>>
>>> ***@***.**** requested changes on this pull request.
>>>
>>> Ana ekranda load more yada pagination yok sadece 20 tane görebiliyorum.
>>>
>>> Bir de bu açtığın RenaCet:IT537_Selin branch'inde yeni commit girersen
>>> tekrardan pull request açmana gerek olmaz. Direk burdan süreç devam
>>> edebilir.
>>>
>>> —
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/mkaanilhan/IT537-2024-Assignment-2/pull/4#pullrequestreview-2165209979>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/BIZDSGRBW5TLUEUGBPF4OW3ZLOBQ5AVCNFSM6AAAAABKQ5B75KVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNRVGIYDSOJXHE>
>>> .
>>> You are receiving this because you authored the thread.Message ID:
>>> ***@***.***>
>>>
>>

2024-07-10 05:23 UTC, mkaanilhan approved these changes
100

2024-08-06 06:36 UTC, closed without merging